language: go

matrix:
  include:
  - go: 1.8
  - go: 1.9
  - go: 1.10
  - go: tip
  allow_failures:
  - go: tip

install:
- # Skip

script:
- go get -t -v ./...
- go vet ./...
- go build
- go test -race -coverprofile=coverage.txt -covermode=atomic ./ ./tests

after_success:
- bash <(curl -s https://codecov.io/bash)
