language: go

matrix:
  include:
  - go: "1.10"
  - go: tip
  allow_failures:
  - go: tip

install:
- # Skip

script:
- mkdir -p $GOPATH/src/roob.re/
- mv $PWD $GOPATH/src/roob.re/goxxy
- cd $GOPATH/src/roob.re/goxxy
- go get -t -v ./...
- go vet ./...
- go build
- go test -race -coverprofile=coverage.txt -covermode=atomic ./ ./tests

after_success:
- bash <(curl -s https://codecov.io/bash)
